config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # READ
  get 'pets', to: 'pets#index', as: :pets
  get 'pets/new', to: 'pets#new', as: :new_pet
  get 'pets/:id', to: 'pets#show', as: :pet
  delete 'pets/:id', to: 'pets#destroy'
  post 'pets', to: 'pets#create'
  get 'pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch 'pets/:id', to: 'pets#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord

  SPECIES = ['Dog', 'Cat', 'Fish', 'Rabbit', 'Turtle', 'Hamster']

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params) # Instantiate a new pet with the values from the form

    @pet.save # Persists the new pet into the DB

    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)

    redirect_to pets_path(@pet)
  end

  def destroy
    @pet.destroy

    redirect_to pets_path
  end

  private
  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :size, :found_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets686</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :size %>
  <%= f.input :found_at %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pets/edit.html.erb
<%= render 'form' %>

<%= link_to 'Go back to all pets', pets_path %>

app/views/pets/index.html.erb
<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to "#{pet.name} (#{pet.species})", pet_path(pet) %></li>
  <% end %>
</ul>

<%= link_to 'Create a new pet', new_pet_path %>

app/views/pets/new.html.erb
<%= render 'form' %>

<%= link_to 'Go back to all pets', pets_path %>

app/views/pets/show.html.erb
<h2><%= @pet.name %>, the <%= @pet.species %></h2>
<p>This is a <%= @pet.size %> fella, and it was found at <%= @pet.found_at.strftime('%d-%m-%Y') %>.</p>

<%= link_to 'Edit', edit_pet_path(@pet) %>
<%= link_to 'Adopt or Cook', pet_path(@pet), method: :delete %>
<%= link_to 'Go back to all pets', pets_path %>